# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b82d23c76fea86d4ea8d162720ccfab11fdca1f0ca94e2a4fb51369101f7326330e5201ad1819e117b61258f401badcdb12e4c34c7a374522a872d658d2811cf

test:
  secret_key_base: 14fb8c6954265afefc8bf576eae4edd0da44b595e9e1725178665866b5e8a44035dd0a0a728094214d829bf1ff962f4a9be3bfdb1c09c136bcbab2c8bf76f9f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
